// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ftrwacqtvhjrbxeafzzm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0cndhY3F0dmhqcmJ4ZWFmenptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNjUzNDMsImV4cCI6MjA2Njg0MTM0M30.tHUsQ9DPOpcNhMjllRDmiekyTnXX4wdWLXtw1-yO68Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});